version: '3'

services:

  mysql:
    image: mysql:5.7
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--max_allowed_packet=128M"
      - "--character-set-server=utf8"
      - "--collation-server=utf8_unicode_ci"
    ports:
      - 3306:3306
    volumes:
      - ${MYSQL_VOLUME:-mysql-volume}:/var/lib/mysql:Z
      - ./configs/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}

  freeradius:
    image: zentekmx/freeradius
    ports:
      - 1812:1812/udp
      - 1813:1813/udp
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASS=${MYSQL_PASSWORD}
      - DB_PORT=${MYSQL_PORT}
      - RADIUS_KEY
      - RAD_CLIENTS
      - RAD_DEBUG

volumes:
  mysql-volume:

